export { DashboardTab } from './DashboardTab';
export { ProcessingTab } from './ProcessingTab';
export { IntegrationTab } from './IntegrationTab';
export { DataTab } from './DataTab';
export { AlertsTab } from './AlertsTab';
export { SettingsTab } from './SettingsTab';
export { MonitoringTab } from './MonitoringTab';
export { ModelsTab } from './ModelsTab';
export { PredictionTab } from './PredictionTab';
