export { DashboardTab } from './DashboardTab';
export { ProcessingTab } from './ProcessingTab';
export { IntegrationTab } from './IntegrationTab';
export { DataTab } from './DataTab';
export { AlertsTab } from './AlertsTab';
export { SettingsTab } from './SettingsTab';
export { MonitoringTab } from './MonitoringTab';
export { ModelsTab } from './ModelsTab';
export { PredictionTab } from './PredictionTab';
export { ParetoTab } from './ParetoTab';
export { ComparisonTab } from './ComparisonTab';
export { default as DataSourcesTab } from './DataSourcesTab';
export { default as UsersTab } from './UsersTab';
export { default as PipelineTab } from './PipelineTab';
export { default as SignalTracerTab } from './SignalTracerTab';
